### ISSUE TITLE
Error "name 'quit_curation' is not defined" using curator_sorting

### ISSUE THREAD

**Issue by smallfade** [AllenInstitute/aics-ml-segmentation#1]
`[2019-09-03 18:12:05,765 - root - 206][DEBUG] --------------------------------------------------------------------------------
[2019-09-03 18:12:05,765 - root - 241][DEBUG] Working Dir:
[2019-09-03 18:12:05,765 - root - 242][DEBUG] 	/home/small/Images
[2019-09-03 18:12:05,765 - root - 243][DEBUG] Command Line:
[2019-09-03 18:12:05,765 - root - 244][DEBUG] 	/home/small/miniconda3/envs/img/bin/curator_sorting --d --raw_path /home/small/Images/laminin_staining/data/ --data_type .tiff --input_ch 3 --seg_path /home/small/Images/laminin_staining/seg_res/ --mask_path /home/small/Images/laminin_staining/mask/ --csv_name /home/small/Images/laminin_staining/curator_sorting_tracker.csv --train_path /home/small/Images/laminin_staining/trainset/ --Normalization 1
[2019-09-03 18:12:05,765 - root - 245][DEBUG] Args:
[2019-09-03 18:12:05,765 - root - 247][DEBUG] 	debug: True
[2019-09-03 18:12:05,765 - root - 247][DEBUG] 	output_dir: ./
[2019-09-03 18:12:05,765 - root - 247][DEBUG] 	struct_ch: 0
[2019-09-03 18:12:05,765 - root - 247][DEBUG] 	xy: 0.108
[2019-09-03 18:12:05,766 - root - 247][DEBUG] 	raw_path: /home/small/Images/laminin_staining/data/
[2019-09-03 18:12:05,766 - root - 247][DEBUG] 	data_type: .tiff
[2019-09-03 18:12:05,766 - root - 247][DEBUG] 	input_channel: 3
[2019-09-03 18:12:05,766 - root - 247][DEBUG] 	seg_path: /home/small/Images/laminin_staining/seg_res/
[2019-09-03 18:12:05,766 - root - 247][DEBUG] 	train_path: /home/small/Images/laminin_staining/trainset/
[2019-09-03 18:12:05,766 - root - 247][DEBUG] 	mask_path: /home/small/Images/laminin_staining/mask/
[2019-09-03 18:12:05,766 - root - 247][DEBUG] 	csv_name: /home/small/Images/laminin_staining/curator_sorting_tracker.csv
[2019-09-03 18:12:05,766 - root - 247][DEBUG] 	Normalization: 1
[2019-09-03 18:12:05,766 - root - 208][DEBUG] --------------------------------------------------------------------------------
the csv file for saving sorting results exists, sorting will be resumed
[2019-09-03 18:12:16,782 - root - 382][ERROR] =============================================
[2019-09-03 18:12:16,783 - root - 384][ERROR] 

Traceback (most recent call last):
  File "/home/small/Images/aics-ml-segmentation/aicsmlsegment/bin/curator/curator_sorting.py", line 379, in main
    exe.execute(args)
  File "/home/small/Images/aics-ml-segmentation/aicsmlsegment/bin/curator/curator_sorting.py", line 297, in execute
    score = gt_sorting(raw_img, seg)
  File "/home/small/Images/aics-ml-segmentation/aicsmlsegment/bin/curator/curator_sorting.py", line 132, in gt_sorting
    cid2 = fig.canvas.mpl_connect('key_press_event', quit_curation)
NameError: name 'quit_curation' is not defined

[2019-09-03 18:12:16,783 - root - 385][ERROR] =============================================
[2019-09-03 18:12:16,783 - root - 386][ERROR] 

name 'quit_curation' is not defined

[2019-09-03 18:12:16,783 - root - 387][ERROR] =============================================
`
It looks like an event callback is missing from your code.

**Comment by smallfade** [comment]
Tried commenting out the lines using 'quit_curation'. It seems ok without it.

**Comment by jxchen01** [comment]
Thanks for your feedback. The "quit curation" is missing. I pushed an update to the repository with curator fixed and more example configuration files. I would be more than happy to help, if you encounter more issues.

**Comment by jxchen01** [comment]
Based on the informatin you provided, it seems like you did the installation by `pip install -e .` . If that is true, to update the package to include the new changes, you can simply do a `git pull` to update the code.
