### ISSUE TITLE
ValueError:  operands could not be broadcast together with remapped shapes [original->remapped]: (4,2) and requested shape (5,2)

### ISSUE THREAD

**Issue by smallfade** [AllenInstitute/aics-ml-segmentation#4]
I was able to train with cpu locally (using a smaller size_in/out), but got the following errors when using GPU nodes to train. I'm using the same trainging set. What goes wrong here?
```
2019-09-16 07:39:28,593 [MainThread] INFO ModelTrainer - {'model': {'name': 'unet_xy'}, 'nchannel': 1, 'nclass': [2, 2, 2], 'size_in': [50, 156, 156], 'size_out': [22, 68, 68], 'checkpoint_dir': '/home/usr1/Images/laminin_staining/checkpoint/', 'resume': None, 'learning_rate': 1e-05, 'weight_decay': 0.005, 'epochs': 400, 'save_every_n_epoch': 50, 'loss': {'name': 'Aux', 'loss_weight': [1, 1, 1], 'ignore_index': None}, 'loader': {'name': 'default', 'datafolder': '/home/usr1/Images/laminin_staining/trainset/', 'batch_size': 8, 'PatchPerBuffer': 200, 'epoch_shuffle': 5, 'NumWorkers': 1}, 'validation': {'metric': 'default', 'leaveout': [0], 'OutputCh': [0, 1, 1, 1, 2, 1], 'validate_every_n_epoch': 25}, 'device': device(type='cuda', index=0)}
model initialization succeeds !
2019-09-16 07:39:34,965 [MainThread] INFO ModelTrainer - Number of learnable params 17729902
start a new training
2019-09-16 07:39:34,966 [MainThread] INFO ModelTrainer - Sending the model to 'cuda:0'
prepare the data ... ...
Traceback (most recent call last):
  File "/usr/local/bin/dl_train", line 11, in <module>
    load_entry_point('aicsmlsegment', 'console_scripts', 'dl_train')()
  File "/aics-ml-segmentation/aicsmlsegment/bin/train.py", line 41, in main
    trainer.train()
  File "/aics-ml-segmentation/aicsmlsegment/training_utils.py", line 231, in train
    train_set_loader = DataLoader(train_loader(train_filenames, loader_config['PatchPerBuffer'], config['size_in'], config['size_out']), num_workers=loader_config['NumWorkers'], batch_size=loader_config['batch_size'], shuffle=True)
  File "/aics-ml-segmentation/aicsmlsegment/DataLoader3D/Universal_Loader.py", line 83, in __init__
    img_pad0 = np.pad(input_img, ((0,0),(0,0),(padding[1],padding[1]),(padding[2],padding[2])), 'constant')
  File "<__array_function__ internals>", line 6, in pad
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/arraypad.py", line 741, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/arraypad.py", line 516, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/stride_tricks.py", line 127, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,2) and requested shape (5,2)

```

**Comment by smallfade** [comment]
Found the issue. If I don't install the classic segmenter, the ml segmenter will use a different aicsimageio, which will produce a different data shape when reading the tif.
